CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=80
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=1
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2